### ISSUE TITLE
报错：cannot import name ‘_imaging’ from 'PIL'

### ISSUE THREAD

**Issue by lrhwind** [bladedream123/smartcrypto_v1.0#1]
启动报错！

F:\soft\python\smartcrypto_v1.0>python smartcrypto.py
Traceback (most recent call last):
  File "F:\soft\python\smartcrypto_v1.0\smartcrypto.py", line 16, in <module>
    from PIL import Image, ImageTk # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\soft\python\smartcrypto_v1.0\libs\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (F:\soft\python\smartcrypto_v1.0\libs\PIL\__init__.py)

**Comment by lrhwind** [comment]
python 版本：
F:\soft\python\smartcrypto_v1.0>python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
